server:
  port: "8080"
  env: "development"
  crt: "tests/localhost.crt"
  key: "tests/localhost.key"
  static_files: "statics"

database:
  host: "localhost"
  port: "5433"
  user: "postgres"
  password: "270153"
  name: "postgres"

wechat:
  app_id: "wx937c1c53ceabe38b"
  app_secret: "ad2225a5932ee1d94e8471ad695a7122"
